import React from "react";

export const metadata = {
  title: "Next.js Routing",
  description: "Generated by Shamuoon Haider",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
