import "./globals.css";
import { Metadata } from "next";

interface Props {
  children: React.ReactNode;
}
export const metadata: Metadata = {
  title: {
    default: "nextjs routing",
    template: "%s | nextjs routing",
  },
  description: "Generated by Next.js",
};

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="en">
      <header className="bg-amber-400 text-black h-20 flex items-center px-10 ">
        <h1 className="text-4xl font-bold">Header</h1>
      </header>
      <body>{children}</body>
      <footer className="bg-rose-400 text-black h-20 flex items-center px-10 ">
        <h1 className="text-4xl font-bold">Footer</h1>
      </footer>{" "}
    </html>
  );
};

export default RootLayout;
